# Generated by Django 4.0.2 on 2022-03-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opiskelijat',
            fields=[
                ('opiskelijanro', models.IntegerField(primary_key=True, serialize=False)),
                ('etunimi', models.CharField(max_length=50)),
                ('sukunimi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tyokalut',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lainaukset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lainausaika', models.DateTimeField()),
                ('opiskelija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.opiskelijat')),
                ('tyokalu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.tyokalut')),
            ],
        ),
    ]
