# Generated by Django 4.0.3 on 2022-03-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Henkilo',
            fields=[
                ('henkilo_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('etunimi', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Henkilö',
                'verbose_name_plural': 'Henkilöt',
            },
        ),
        migrations.CreateModel(
            name='Rooli',
            fields=[
                ('roolinimitys', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Rooli',
                'verbose_name_plural': 'Roolit',
            },
        ),
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('viivakoodi', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tuote_id', models.IntegerField(default=1)),
                ('nimike', models.CharField(max_length=50)),
                ('hankintapaikka', models.CharField(max_length=50)),
                ('kustannuspaikka', models.CharField(max_length=10)),
                ('tuotekuva', models.BinaryField()),
            ],
            options={
                'verbose_name': 'Tuote',
                'verbose_name_plural': 'Tuotteet',
            },
        ),
        migrations.CreateModel(
            name='Tuoteryhma',
            fields=[
                ('tuoteryhma_id', models.AutoField(primary_key=True, serialize=False)),
                ('tuoteryhma_nimi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tuoteryhmä',
                'verbose_name_plural': 'Tuoteryhmät',
            },
        ),
        migrations.CreateModel(
            name='Varasto',
            fields=[
                ('varasto_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('varaston_nimi', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Varasto',
                'verbose_name_plural': 'Varastot',
            },
        ),
        migrations.CreateModel(
            name='Varastotyyppi',
            fields=[
                ('varastotyyppi_id', models.AutoField(primary_key=True, serialize=False)),
                ('varastotyyppi_nimi', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Varastotyyppi',
                'verbose_name_plural': 'Varastotyypit',
            },
        ),
        migrations.CreateModel(
            name='Varastotapahtuma',
            fields=[
                ('tapahtuma_id', models.AutoField(primary_key=True, serialize=False)),
                ('arkistotunnus', models.CharField(max_length=50)),
                ('maara', models.IntegerField()),
                ('aikaleima', models.DateField()),
                ('palautuspaiva', models.DateField()),
                ('asiakas_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiakas', to='varasto.henkilo')),
                ('varasto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.varasto')),
                ('varastonhoitaja_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.henkilo')),
                ('viivakoodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.tuote')),
            ],
            options={
                'verbose_name': 'Varastotapahtuma',
                'verbose_name_plural': 'Varastotapahtumat',
            },
        ),
        migrations.AddField(
            model_name='varasto',
            name='varastotyyppi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.varastotyyppi'),
        ),
        migrations.AddField(
            model_name='tuote',
            name='tuoteryhma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='varasto.tuoteryhma'),
        ),
        migrations.AddField(
            model_name='henkilo',
            name='roolinimitys',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='varasto.rooli'),
        ),
    ]
