# Generated by Django 4.0.3 on 2022-04-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuoteryhma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nimi', models.CharField(max_length=50, verbose_name='Nimi')),
            ],
            options={
                'verbose_name': 'Tuoteryhmä',
                'verbose_name_plural': 'Tuoteryhmät',
            },
        ),
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viivakoodi', models.CharField(max_length=30, verbose_name='Viivakoodi')),
                ('nimike', models.CharField(max_length=50, verbose_name='Nimike')),
                ('maara', models.IntegerField(verbose_name='Määrä')),
                ('hankintapaikka', models.CharField(max_length=50, verbose_name='Hankintapaikka')),
                ('kustannuspaikka', models.CharField(max_length=10, verbose_name='Kustannuspaikka')),
                ('tuotekuva', models.BinaryField(verbose_name='Tuotekuva')),
                ('tuoteryhma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuotteet.tuoteryhma', verbose_name='Tuoteryhmä')),
            ],
            options={
                'verbose_name': 'Tuote',
                'verbose_name_plural': 'Tuotteet',
            },
        ),
    ]
