# Generated by Django 4.0.3 on 2022-05-05 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuotteet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuote',
            options={'ordering': ['tuoteryhma', 'nimike'], 'verbose_name': 'Tuote', 'verbose_name_plural': 'Tuotteet'},
        ),
        migrations.CreateModel(
            name='TuoteOld',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nimike', models.CharField(max_length=50, verbose_name='Nimike')),
                ('maara', models.IntegerField(verbose_name='Määrä')),
                ('hankintapaikka', models.CharField(max_length=50, verbose_name='Hankintapaikka')),
                ('kustannuspaikka', models.CharField(max_length=10, verbose_name='Kustannuspaikka')),
                ('tuotekuva', models.BinaryField(verbose_name='Tuotekuva')),
                ('viivakoodi_string', models.CharField(max_length=30, verbose_name='Viivakoodi')),
                ('viivakoodi_img', models.BinaryField(verbose_name='Viivakoodi')),
                ('lisaysaika', models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika')),
                ('poistettu', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Poistettu')),
                ('lisaaja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lisaaja_oli', to=settings.AUTH_USER_MODEL, verbose_name='Lisääjä')),
                ('poistaja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Poistaja')),
                ('tuoteryhma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuoteryhma_oli', to='tuotteet.tuoteryhma', verbose_name='Tuoteryhmä')),
            ],
            options={
                'verbose_name': 'Vanha tuote',
                'verbose_name_plural': 'Vanhat tuotteet',
                'ordering': ['tuoteryhma', 'nimike'],
                'abstract': False,
            },
        ),
    ]
