# Generated by Django 4.0.3 on 2022-05-10 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuotteet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuote',
            name='poistaja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tuotteen_poistaja', to=settings.AUTH_USER_MODEL, verbose_name='Tuotteen poistaja'),
        ),
        migrations.AddField(
            model_name='tuote',
            name='poistettu',
            field=models.BooleanField(default=False, verbose_name='Poistettu'),
        ),
        migrations.AddField(
            model_name='tuote',
            name='poistoaika',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Poistoaika'),
        ),
        migrations.AddField(
            model_name='tuoteryhma',
            name='avoin',
            field=models.BooleanField(default=True, verbose_name='Avoin'),
        ),
        migrations.AddField(
            model_name='tuoteryhma',
            name='poistaja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poistaja', to=settings.AUTH_USER_MODEL, verbose_name='Ryhmän poistaja'),
        ),
        migrations.AddField(
            model_name='tuoteryhma',
            name='poistoaika',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Poistettu'),
        ),
        migrations.DeleteModel(
            name='TuoteOld',
        ),
    ]
