# Generated by Django 4.0.3 on 2022-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0002_tuote_poistaja_tuote_poistettu_tuote_poistoaika_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuoteryhma',
            name='avoin',
        ),
        migrations.AddField(
            model_name='tuoteryhma',
            name='poistettu',
            field=models.BooleanField(default=False, verbose_name='Poistettu'),
        ),
        migrations.AlterField(
            model_name='tuoteryhma',
            name='poistoaika',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Poistoaika'),
        ),
    ]
