# Generated by Django 4.0.3 on 2022-05-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0003_remove_tuoteryhma_avoin_tuoteryhma_poistettu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuote',
            name='viivakoodi_img',
        ),
    ]
