# Generated by Django 4.0.3 on 2022-05-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0004_remove_tuote_viivakoodi_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuote',
            name='tuotekuva',
            field=models.ImageField(upload_to='', verbose_name='Tuotekuva'),
        ),
    ]
