# Generated by Django 4.0.3 on 2022-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0005_alter_tuote_tuotekuva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuote',
            old_name='viivakoodi_string',
            new_name='viivakoodi_plaintxt',
        ),
        migrations.AddField(
            model_name='tuote',
            name='viivakoodi_encoded',
            field=models.CharField(default=0, max_length=30, verbose_name='Viivakoodi128'),
            preserve_default=False,
        ),
    ]
