# Generated by Django 4.0.5 on 2022-07-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0006_rename_viivakoodi_string_tuote_viivakoodi_plaintxt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuoteryhmaNimiMaara',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tuotteet.tuoteryhma',),
        ),
    ]
