# Generated by Django 4.0.3 on 2022-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kayttaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('opiskelijanumero', models.CharField(max_length=5, unique=True, verbose_name='Opiskelijanumero')),
                ('etunimi', models.CharField(max_length=64)),
                ('sukunimi', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Sähköposti')),
                ('aktiivinen', models.BooleanField(default=True, verbose_name='Aktiivinen')),
                ('staff', models.BooleanField(default=False, verbose_name='Henkilökunta')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('liittynyt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Käyttäjä',
                'verbose_name_plural': 'Käyttäjät',
            },
        ),
    ]
