# Generated by Django 4.0.3 on 2022-05-09 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tuotteet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Varastotapahtuma',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('arkistotunnus', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Arkistotunnus')),
                ('maara', models.IntegerField(verbose_name='Määrä')),
                ('aikaleima', models.DateTimeField(auto_now_add=True, verbose_name='Aikaleima')),
                ('viim_palautuspaiva', models.DateField(verbose_name='Viim. palautuspäivä')),
                ('avoin', models.BooleanField(default=True, verbose_name='Avoin')),
                ('palautettu', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Palautettu')),
                ('asiakas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiakas', to=settings.AUTH_USER_MODEL, verbose_name='Asiakas')),
                ('tuote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuotteet.tuote', verbose_name='Tuote')),
                ('varastonhoitaja', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='varastonhoitaja', to=settings.AUTH_USER_MODEL, verbose_name='Varastonhoitaja')),
                ('varastonhoitaja_palautus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='varastonhoitaja_palautus', to=settings.AUTH_USER_MODEL, verbose_name='Palautuksen varastonhoitaja')),
            ],
            options={
                'verbose_name': 'Varastotapahtuma',
                'verbose_name_plural': 'Varastotapahtumat',
                'ordering': ['asiakas'],
            },
        ),
    ]
