# Generated by Django 4.0.3 on 2022-04-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuotteet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varastotapahtuma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arkistotunnus', models.CharField(editable=False, max_length=37, unique=True, verbose_name='Arkistotunnus')),
                ('maara', models.IntegerField(verbose_name='Määrä')),
                ('aikaleima', models.DateTimeField(auto_now_add=True, verbose_name='Aikaleima')),
                ('palautuspaiva', models.DateField(verbose_name='Palautuspäivä')),
                ('asiakas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiakas', to=settings.AUTH_USER_MODEL, verbose_name='Asiakas')),
                ('tuote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuotteet.tuote', verbose_name='Tuote')),
                ('varastonhoitaja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varastonhoitaja', to=settings.AUTH_USER_MODEL, verbose_name='Varastonhoitaja')),
            ],
            options={
                'verbose_name': 'Varastotapahtuma',
                'verbose_name_plural': 'Varastotapahtumat',
            },
        ),
    ]
