# Generated by Django 4.0.3 on 2022-04-22 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='palautuspaiva',
            field=models.DateField(default=datetime.datetime(2022, 5, 6, 10, 15, 8, 351438, tzinfo=utc), verbose_name='Palautuspäivä'),
        ),
    ]
