# Generated by Django 4.0.3 on 2022-04-05 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='asiakas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiakas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='varastonhoitaja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varastonhoitaja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Henkilo',
        ),
    ]
