# Generated by Django 4.0.3 on 2022-04-12 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='aikaleima',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Aikaleima'),
        ),
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='palautuspaiva',
            field=models.DateField(default=datetime.datetime(2022, 4, 26, 12, 2, 7, 868176), verbose_name='Palautuspäivä'),
        ),
    ]
