# Generated by Django 4.0.3 on 2022-04-20 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='palautuspaiva',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 9, 14, 58, 196907, tzinfo=utc), verbose_name='Palautuspäivä'),
        ),
    ]
