# Generated by Django 4.0.3 on 2022-05-03 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='arkistotunnus',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Arkistotunnus'),
        ),
    ]
