# Generated by Django 4.0.3 on 2022-05-04 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tuotteet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varasto', '0002_alter_varastotapahtuma_arkistotunnus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varastotapahtuma',
            options={'ordering': ['asiakas'], 'verbose_name': 'Varastotapahtuma', 'verbose_name_plural': 'Varastotapahtumat'},
        ),
        migrations.CreateModel(
            name='VarastotapahtumaOld',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arkistotunnus', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Arkistotunnus')),
                ('maara', models.IntegerField(verbose_name='Määrä')),
                ('aikaleima', models.DateTimeField(auto_now_add=True, verbose_name='Aikaleima')),
                ('palautuspaiva', models.DateField(verbose_name='Palautuspäivä')),
                ('palautettu', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Palautettu')),
                ('poistettu', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Poistettu')),
                ('asiakas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asiakas_oli', to=settings.AUTH_USER_MODEL, verbose_name='Asiakas')),
                ('tuote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuotteet.tuote', verbose_name='Tuote')),
                ('varastonhoitaja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varastonhoitaja_oli', to=settings.AUTH_USER_MODEL, verbose_name='Varastonhoitaja')),
            ],
            options={
                'verbose_name': 'Vanha varastotapahtuma',
                'verbose_name_plural': 'Vanhat varastotapahtumat',
                'ordering': ['asiakas'],
                'abstract': False,
            },
        ),
    ]
