# Generated by Django 4.0.3 on 2022-05-05 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varasto', '0003_alter_varastotapahtuma_options_varastotapahtumaold'),
    ]

    operations = [
        migrations.AddField(
            model_name='varastotapahtumaold',
            name='varastonhoitaja_poisto_palautus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='varastonhoitaja_poisto_palautus', to=settings.AUTH_USER_MODEL, verbose_name='Varastonhoitaja poisto/palautus'),
            preserve_default=False,
        ),
    ]
