# Generated by Django 4.0.3 on 2022-04-19 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0004_alter_profiili_options_alter_profiili_kuva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='palautuspaiva',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 9, 41, 28, 653681, tzinfo=utc), verbose_name='Palautuspäivä'),
        ),
    ]
