# Generated by Django 4.0.3 on 2022-04-19 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0005_alter_varastotapahtuma_palautuspaiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='palautuspaiva',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 9, 58, 51, 697716, tzinfo=utc), verbose_name='Palautuspäivä'),
        ),
        migrations.DeleteModel(
            name='Profiili',
        ),
    ]
