# Generated by Django 4.0.3 on 2022-04-19 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('varasto', '0006_alter_varastotapahtuma_palautuspaiva_delete_profiili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='arkistotunnus',
            field=models.CharField(max_length=37, verbose_name='Arkistotunnus'),
        ),
        migrations.AlterField(
            model_name='varastotapahtuma',
            name='palautuspaiva',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 11, 24, 24, 403480, tzinfo=utc), verbose_name='Palautuspäivä'),
        ),
    ]
